development:
  adapter: postgresql
  encoding: unicode
  database: new-pull-list_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: new-pull-list_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: new-pull-list_production
  pool: 5